name: "octopus"
version: "0.1.0"
usage: "Choose value files from subcharts"
description: |-
  This plugin provides access to subcharts value files
useTunnel: false
command: "$HELM_PLUGIN_DIR/octopus"
