on:
  release:
    types: [ published ]
name: Release
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set version
        run: echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      - name: Build
        run: make dist
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ env.VERSION }}
          args: '/home/riccardo/src/helm-octopus/release/helm-octopus*.tgz'